[".dotfiles/external/git-completion.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "24h"
[".dotfiles/fonts/Fira Code Regular Nerd Font Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/complete/Fira%20Code%20Regular%20Nerd%20Font%20Complete.ttf"
    refreshPeriod = "24h"
