[".dotfiles/external/git-completion.bash"]
    type = "file"
    url = "https://raw.githubusercontent.com/git/git/master/contrib/completion/git-completion.bash"
    refreshPeriod = "24h"
{{ if .env.mac -}}
[".dotfiles/fonts/Fira Code Retina Nerd Font Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Retina/FiraCodeNerdFont-Retina.ttf"
    refreshPeriod = "24h"
{{ end -}}
[".dotfiles/fonts/Fira Code Regular Nerd Font Complete.ttf"]
    type = "file"
    url = "https://github.com/ryanoasis/nerd-fonts/raw/master/patched-fonts/FiraCode/Regular/FiraCodeNerdFont-Regular.ttf"
    refreshPeriod = "24h"